version: '2.0'

volumes:
  opt-splunk-etc:
  opt-splunk-var:
  opt-forwarder-1-etc:
  opt-forwarder-1-var:
  opt-forwarder-2-etc:
  opt-forwarder-2-var:

services:
  splunkenterprise:
    image: splunk/splunk:7.0.3
    container_name: server
    hostname: splunkenterprise-docker
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_DEPLOY_SERVER: 'true'
    volumes:
      - /data/splunk/opt-splunk-etc:/opt/splunk/etc
      - /data/splunk/opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"

  forwarder-1:
    image: ospost/lenovo-splunk-forwarder:7.0.3
    container_name: forwarder-1
    hostname: splunkforwarder-1-docker
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_FORWARD_SERVER_ARGS: '-method clone'
      SPLUNK_FORWARD_SERVER: 'splunkenterprise:9997'
      SPLUNK_DEPLOYMENT_SERVER: 'splunkenterprise:8089'
      SPLUNK_ENABLE_LISTEN: 9997
    volumes:
      - /data/forwarder-1/opt-forwarder-1-etc:/opt/splunk/etc
      - /data/forwarder-1/opt-forwarder-1-var:/opt/splunk/var
    ports:
      - "9997:9997"

  forwarder-2:
    image: ospost/lenovo-splunk-forwarder:7.0.3
    container_name: forwarder-2
    hostname: splunkforwarder-2-docker
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_FORWARD_SERVER_ARGS: '-method clone'
      SPLUNK_FORWARD_SERVER: 'splunkenterprise:9997'
      SPLUNK_DEPLOYMENT_SERVER: 'splunkenterprise:8089'
      SPLUNK_ENABLE_LISTEN: 9998
    volumes:
      - /data/forwarder-2/opt-forwarder-2-etc:/opt/splunk/etc
      - /data/forwarder-2/opt-forwarder-2-var:/opt/splunk/var
    ports:
      - "9998:9998"



